# Generated by Django 5.2.8 on 2025-12-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='budget',
            field=models.IntegerField(default=0),
        ),
    ]
