# Generated by Django 5.2.8 on 2025-11-30 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='main.user')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_assignments', to='main.user')),
            ],
        ),
    ]
